[tox]
envlist =
    py{310,311,312,313,314}-django{52}

skip_missing_interpreters = true

[testenv]
deps =
    django52: Django>=5.2,<5.3

    pytest-django>=4.11.1
    django-picklefield
    mysqlclient

    pytest-cov
    pytz
    xlwt

commands =
    pytest -ra --cov form_designer --cov-report term --cov-report html form_designer {posargs}
setenv =
    DEBUG = 1
    PYTHONPATH = {toxinidir}
    DJANGO_SETTINGS_MODULE = dfd_tests.settings
passenv =
    DATABASE*

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314
