name: CI
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10", "3.13"]
        DATABASE: ["mysql", "sqlite"]
    steps:
      - uses: astral-sh/setup-uv@3259c6206f993105e3a61b142c2d97bf4b9ef83d # v7.1.0
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: actions/checkout@v5
      - run: uvx --with=tox-gh-actions --with=tox-uv tox -v
        env:
          DATABASE_USER: root
          DATABASE_PASSWORD: root
          DJANGO_SETTINGS_MODULE: dfd_tests.settings
